(deftheme blendoit-light
  "Created 2020-08-12.")

(custom-theme-set-faces
 'blendoit-light
 '(variable-pitch ((t (:family "Liberation Sans"))))
 '(escape-glyph ((((background dark)) (:foreground "cyan")) (((type pc)) (:foreground "magenta")) (t (:foreground "brown"))))
 '(homoglyph ((((background dark)) (:foreground "cyan")) (((type pc)) (:foreground "magenta")) (t (:foreground "brown"))))
 '(minibuffer-prompt ((((background dark)) (:foreground "cyan")) (((type pc)) (:foreground "magenta")) (t (:foreground "medium blue"))))
 '(highlight ((t (:underline nil :foreground "#ffffff" :background "#454545"))))
 '(region ((t (:background "light gray"))))
 '(shadow ((t (:foreground "dark slate gray"))))
 '(secondary-selection ((((class color) (min-colors 88) (background light)) (:background "yellow1")) (((class color) (min-colors 88) (background dark)) (:background "SkyBlue4")) (((class color) (min-colors 16) (background light)) (:background "yellow")) (((class color) (min-colors 16) (background dark)) (:background "SkyBlue4")) (((class color) (min-colors 8)) (:foreground "black" :background "cyan")) (t (:inverse-video t))))
 '(trailing-whitespace ((((class color) (background light)) (:background "red1")) (((class color) (background dark)) (:background "red1")) (t (:inverse-video t))))
 '(font-lock-builtin-face ((((class grayscale) (background light)) (:weight bold :foreground "LightGray")) (((class grayscale) (background dark)) (:weight bold :foreground "DimGray")) (((class color) (min-colors 88) (background light)) (:foreground "dark slate blue")) (((class color) (min-colors 88) (background dark)) (:foreground "LightSteelBlue")) (((class color) (min-colors 16) (background light)) (:foreground "Orchid")) (((class color) (min-colors 16) (background dark)) (:foreground "LightSteelBlue")) (((class color) (min-colors 8)) (:weight bold :foreground "blue")) (t (:weight bold))))
 '(font-lock-comment-delimiter-face ((t (:foreground "dim gray" :inherit font-lock-comment-face))))
 '(font-lock-comment-face ((t (:slant italic :foreground "slate gray" :inherit variable-pitch))))
 '(font-lock-constant-face ((t (:foreground "dark cyan"))))
 '(font-lock-function-name-face ((((class color) (min-colors 88) (background light)) (:foreground "Blue1")) (((class color) (min-colors 88) (background dark)) (:foreground "LightSkyBlue")) (((class color) (min-colors 16) (background light)) (:foreground "Blue")) (((class color) (min-colors 16) (background dark)) (:foreground "LightSkyBlue")) (((class color) (min-colors 8)) (:weight bold :foreground "blue")) (t (:weight bold :inverse-video t))))
 '(font-lock-keyword-face ((t (:foreground "DodgerBlue4"))))
 '(font-lock-negation-char-face ((t nil)))
 '(font-lock-preprocessor-face ((t (:inherit (font-lock-builtin-face)))))
 '(font-lock-regexp-grouping-backslash ((t (:inherit (bold)))))
 '(font-lock-regexp-grouping-construct ((t (:inherit (bold)))))
 '(font-lock-string-face ((t (:foreground "DodgerBlue1"))))
 '(font-lock-type-face ((t (:foreground "ForestGreen"))))
 '(font-lock-variable-name-face ((t (:foreground "sienna"))))
 '(font-lock-warning-face ((t (:inherit (error)))))
 '(link-visited ((t (:foreground "magenta4" :inherit (link)))))
 '(fringe ((t (:background "grey95"))))
 '(header-line ((t (:box nil :foreground "grey20" :background "grey90" :inherit (mode-line)))))
 '(tooltip ((t (:foreground "black" :background "lightyellow" :inherit (variable-pitch)))))
 '(mode-line ((t (:box (:line-width -1 :color nil :style released-button) :foreground "black" :background "grey75"))))
 '(mode-line-buffer-id ((t (:weight bold))))
 '(mode-line-emphasis ((t (:weight bold))))
 '(mode-line-highlight ((((class color) (min-colors 88)) (:box (:line-width 2 :color "grey40" :style released-button))) (t (:inherit (highlight)))))
 '(mode-line-inactive ((t (:weight light :box (:line-width -1 :color "grey75" :style nil) :foreground "grey20" :background "grey90" :inherit (mode-line)))))
 '(isearch ((((class color) (min-colors 88) (background light)) (:foreground "lightskyblue1" :background "magenta3")) (((class color) (min-colors 88) (background dark)) (:foreground "brown4" :background "palevioletred2")) (((class color) (min-colors 16)) (:foreground "cyan1" :background "magenta4")) (((class color) (min-colors 8)) (:foreground "cyan1" :background "magenta4")) (t (:inverse-video t))))
 '(isearch-fail ((((class color) (min-colors 88) (background light)) (:background "RosyBrown1")) (((class color) (min-colors 88) (background dark)) (:background "red4")) (((class color) (min-colors 16)) (:background "red")) (((class color) (min-colors 8)) (:background "red")) (((class color grayscale)) (:foreground "grey")) (t (:inverse-video t))))
 '(lazy-highlight ((t (:background "paleturquoise"))))
 '(match ((((class color) (min-colors 88) (background light)) (:background "yellow1")) (((class color) (min-colors 88) (background dark)) (:background "RoyalBlue3")) (((class color) (min-colors 8) (background light)) (:foreground "black" :background "yellow")) (((class color) (min-colors 8) (background dark)) (:foreground "white" :background "blue")) (((type tty) (class mono)) (:inverse-video t)) (t (:background "gray"))))
 '(next-error ((t (:inherit region))))
 '(query-replace ((t (:inherit (isearch)))))
 '(org-formula ((t (:inherit org-table))))
 '(org-meta-line ((t (:foreground "DodgerBlue3" :family "Hermit"))))
 '(org-document-title ((t (:width normal :height 2.0 :weight bold :slant normal :underline nil :inherit default))))
 '(org-level-1 ((t (:weight bold :height 1.6 :inherit fixed-pitch))))
 '(org-level-2 ((t (:weight bold :height 1.4 :inherit fixed-pitch))))
 '(org-level-3 ((t (:height 1.2 :weight bold :inherit fixed-pitch))))
 '(org-level-4 ((t (:height 1.1 :weight bold :inherit fixed-pitch))))
 '(org-date ((t (:inherit link :foreground "DodgerBlue3" :slant italic :family "Liberation Serif"))))
 '(org-footnote ((t (:foreground "DodgerBlue3" :inherit link))))
 '(org-tag ((t (:inherit link :weight bold :foreground "DodgerBlue3"))))
 '(link ((t (:foreground "blue" :underline t))))
 '(org-document-info-keyword ((t (:inherit org-meta-line))))
 '(dashboard-heading ((t (:inherit font-lock-keyword-face))))
 '(org-todo ((t (:foreground "Red1" :box 2 :weight bold))))
 '(org-done ((t (:foreground "ForestGreen" :box 2 :weight bold))))
 '(org-code ((t (:background "light grey" :foreground "black"))))
 '(org-checkbox-statistics-todo ((t (:inherit org-todo :box nil))))
 '(org-checkbox-statistics-done ((t (:inherit org-done :box nil))))
 '(org-verbatim ((t (:inherit shadow))))
 '(font-lock-doc-face ((t (:inherit font-lock-string-face))))
 '(cursor ((t (:background "red"))))
 '(org-document-info ((t (:weight bold :inherit variable-pitch))))
 '(fixed-pitch ((t (:family "Hack"))))
 '(org-table ((t (:box (:line-width 1 :color "light slate gray") :foreground "dark slate gray" :inherit fixed-pitch))))
 '(org-block ((t (:family "Hermit"))))
 '(default ((t (:background "white" :foreground "black" :height 120 :family "Hermit")))))

(provide-theme 'blendoit-light)
