# -*- mode: org; -*-

#+TITLE: Smart Documents
#+AUTHOR: Marius Peter
#+DATE: <2021-02-09 Tue>
#+EMAIL: smart-documents@tuta.io

#+SETUPFILE: ~/.emacs.d/www/sd-setup.org
# Extra styling for the home page
#+HTML_HEAD: <link rel="stylesheet" type="text/css" href="./css/index.css"/>

#+INCLUDE: ./navbar.html export html

# Make your personal & professional documents 10\times better.

* Perfect documents every time.
:PROPERTIES:
:CUSTOM_ID: perfect-documents
:END:

Focus on your content and let the editor work out the appearance, for
  flawless exports every time.


* Collaboration done right.

Collect collaborators' feedback and create new document versions
through an efficient wizard.

* Link it all together.

Create links between files to keep track of dates, people, tags, and
compile them into neatly filtered agendas---perfect for sharing a
project status or roadmap!

* A single authoritative document.

Each document can be declined into a report, a presentation
summarizing the document's outline, or a website page that can be
added to your organization's internal wiki.

* Program your documents.

Program your documents in your favorite language thanks to the power
of [[https://orgmode.org/worg/org-contrib/babel/intro.html][Org Babel]].

* Download

You can download the current development snapshot on GitHub at
[[https://github.com/Blendoit/.emacs.d]].

* Support this project

For all inquiries related to donations, please send an e-mail to
[[mailto:smart-documents@tuta.io][smart-documents@tuta.io]]
