# -*- mode: org; -*-

#+TITLE: Smart Documents
#+AUTHOR: Marius Peter
#+DATE: <2021-02-09 Tue>

#+SETUPFILE: ~/.emacs.d/www/sd-setup.org
#+INCLUDE: ./topbar.html export html
# Extra styling for the home page
#+HTML_HEAD: <link rel="stylesheet" type="text/css" href="./css/index.css"/>

* Perfect documents every time.

Focus on your content and let the editor work out the appearance, for
flawless exports every time.

Program your documents in your favorite language thanks to the power
of [[https://orgmode.org/worg/org-contrib/babel/intro.html][Org Babel]].

* Collaboration done right.

Collect collaborators' feedback and create new document versions
through an efficient wizard.

* Link it all together.

Create links between files to keep track of dates, people, tags, and
compile them into neatly filtered agendas---perfect for sharing a
project status or roadmap!

* A single authoritative document.

Each document can be declined into a report, a presentation
summarizing the document's outline, or a website page that can be
added to your organization's internal wiki.

* Program your documents.

Unleash the power of /literate programming/ through Org mode.

* Download

You can download the current development snapshot on GitHub at
[[https://github.com/Blendoit/.emacs.d]].

* Donate

Support the development of this project at the following places:

- Venmo :: =@Blendoit=
- CashApp :: =$MariusPeter=
- PayPal :: [[mailto:mariuspeter.blendux@gmail.com][mariuspeter.blendux@gmail.com]]
