(deftheme blendoit-light
  "Created 2020-11-05.")

(custom-theme-set-faces
 'blendoit-light
 '(cursor ((t (:background "red"))))
 '(fixed-pitch ((t (:family "Hack"))))
 '(variable-pitch ((t (:family "Public Sans"))))
 '(escape-glyph ((((background dark)) (:foreground "cyan")) (((type pc)) (:foreground "magenta")) (t (:foreground "brown"))))
 '(homoglyph ((((background dark)) (:foreground "cyan")) (((type pc)) (:foreground "magenta")) (t (:foreground "brown"))))
 '(minibuffer-prompt ((t (:inherit org-meta-line))))
 '(highlight ((t (:background "deep sky blue" :foreground "white"))))
 '(region ((t (:background "gainsboro"))))
 '(shadow ((t (:foreground "light slate gray"))))
 '(secondary-selection ((((class color) (min-colors 88) (background light)) (:background "yellow1")) (((class color) (min-colors 88) (background dark)) (:background "SkyBlue4")) (((class color) (min-colors 16) (background light)) (:background "yellow")) (((class color) (min-colors 16) (background dark)) (:background "SkyBlue4")) (((class color) (min-colors 8)) (:foreground "black" :background "cyan")) (t (:inverse-video t))))
 '(trailing-whitespace ((((class color) (background light)) (:background "red1")) (((class color) (background dark)) (:background "red1")) (t (:inverse-video t))))
 '(font-lock-builtin-face ((t (:foreground "dark slate blue"))))
 '(font-lock-comment-delimiter-face ((t (:foreground "slate gray"))))
 '(font-lock-comment-face ((t (:foreground "light slate gray" :slant italic))))
 '(font-lock-constant-face ((t (:foreground "dark cyan"))))
 '(font-lock-function-name-face ((((class color) (min-colors 88) (background light)) (:foreground "Blue1")) (((class color) (min-colors 88) (background dark)) (:foreground "LightSkyBlue")) (((class color) (min-colors 16) (background light)) (:foreground "Blue")) (((class color) (min-colors 16) (background dark)) (:foreground "LightSkyBlue")) (((class color) (min-colors 8)) (:weight bold :foreground "blue")) (t (:weight bold :inverse-video t))))
 '(font-lock-keyword-face ((t (:foreground "slate blue"))))
 '(font-lock-negation-char-face ((t nil)))
 '(font-lock-preprocessor-face ((t (:inherit (font-lock-builtin-face)))))
 '(font-lock-regexp-grouping-backslash ((t (:inherit (bold)))))
 '(font-lock-regexp-grouping-construct ((t (:inherit (bold)))))
 '(font-lock-string-face ((t (:foreground "DodgerBlue1"))))
 '(font-lock-type-face ((t (:foreground "ForestGreen"))))
 '(font-lock-variable-name-face ((t (:foreground "sienna"))))
 '(font-lock-warning-face ((t (:inherit (error)))))
 '(fringe ((t (:background "grey95"))))
 '(header-line ((t (:box nil :inherit mode-line :background "steel blue" :foreground "white"))))
 '(tooltip ((t (:foreground "black" :background "lightyellow" :inherit (variable-pitch)))))
 '(mode-line ((t (:box (:line-width -1 :style released-button) :foreground "white" :background "steel blue" :height 1.2 :family "Hack"))))
 '(mode-line-buffer-id ((t (:weight bold))))
 '(mode-line-emphasis ((t (:weight bold))))
 '(mode-line-highlight ((t (:box (:line-width 2 :color "grey40" :style released-button)))))
 '(mode-line-inactive ((t (:box (:line-width -1 :color "gainsboro") :foreground "gainsboro" :background "SteelBlue4" :height 1.2 :family "Hermit"))))
 '(isearch ((t (:background "DodgerBlue1" :foreground "white"))))
 '(isearch-fail ((t (:background "RosyBrown1"))))
 '(lazy-highlight ((t (:foreground "DodgerBlue1" :box 2))))
 '(match ((t (:background "yellow1"))))
 '(next-error ((t (:inherit region))))
 '(query-replace ((t (:inherit (isearch)))))
 '(swiper-match-face-1 ((t (:inherit lazy-highlight))))
 '(swiper-match-face-2 ((t (:inherit (isearch)))))
 '(swiper-match-face-3 ((t (:inherit isearch))))
 '(swiper-match-face-4 ((t (:inherit isearch))))
 '(ivy-minibuffer-match-face-1 ((t (:inherit swiper-match-face-1))))
 '(ivy-minibuffer-match-face-2 ((t (:inherit swiper-match-face-2))))
 '(ivy-minibuffer-match-face-3 ((t (:inherit swiper-match-face-3))))
 '(ivy-minibuffer-match-face-4 ((t (:inherit swiper-match-face-4))))
 '(ivy-minibuffer-match-highlight ((t (:inherit highlight))))
 '(org-formula ((t (:inherit org-table))))
 '(org-meta-line ((t (:foreground "SteelBlue" :family "Hermit"))))
 '(org-document-title ((t (:weight bold :height 2.0 :family "Jost*"))))
 '(org-footnote ((t (:inherit link))))
 '(org-document-info-keyword ((t (:inherit org-meta-line))))
 '(org-code ((t (:background "light grey" :foreground "black" :height 0.9 :family "Hack"))))
 '(org-checkbox-statistics-todo ((t (:inherit org-checkbox :foreground "tomato"))))
 '(org-checkbox-statistics-done ((t (:inherit org-checkbox :foreground "ForestGreen"))))
 '(org-verbatim ((t (:foreground "DodgerBlue1" :height 0.9 :foundry "Hack"))))
 '(font-lock-doc-face ((t (:inherit font-lock-string-face :Family "Public Sans"))))
 '(org-document-info ((t (:weight bold))))
 '(org-table ((t (:height 0.8 :family "Hack"))))
 '(org-block ((t (:height 0.8 :family "Hermit"))))
 '(org-special-keyword ((t (:background "white" :weight bold :inherit org-meta-line))))
 '(org-level-1 ((t (:foreground "black" :weight bold :height 1.6 :family "Jost*"))))
 '(org-level-2 ((t (:foreground "gray30" :weight bold :height 1.4))))
 '(org-level-3 ((t (:foreground "gray45" :weight bold :height 1.2))))
 '(org-level-4 ((t (:foreground "gray60" :weight bold :height 1.1))))
 '(org-level-5 ((t (:foreground "gray75" :weight bold :height 1.0))))
 '(org-level-6 ((t (:inherit org-level-5))))
 '(org-level-7 ((t (:inherit org-level-5))))
 '(org-level-8 ((t (:inherit org-level-5))))
 '(org-checkbox ((t (:weight bold :inherit org-meta-line))))
 '(org-todo ((t (:background "tomato" :foreground "White" :weight bold :height 1.2 :family "Hermit"))))
 '(org-done ((t (:background "ForestGreen" :foreground "White" :weight bold :height 1.2 :family "Hermit"))))
 '(org-date ((t (:foreground "steel blue" :family "Hermit"))))
 '(Info-quoted ((t (:inherit org-block))))
 '(org-priority ((t (:inherit org-meta-line))))
 '(org-drawer ((t (:inherit org-meta-line))))
 '(tab-line ((t (:background "gainsboro" :family "Hack"))))
 '(tab-line-tab ((default (:inherit (tab-line))) (((class color) (min-colors 88)) (:box (:line-width 1 :color nil :style released-button))) (t (:inverse-video nil))))
 '(tab-line-tab-inactive ((t (:inherit tab-line-tab :background "white" :foreground "steel blue"))))
 '(tab-line-tab-current ((t (:inherit tab-line-tab :background "grey85" :foreground "red"))))
 '(tab-line-close-highlight ((t (:foreground "red"))))
 '(tab-line-highlight ((default (:inherit (tab-line-tab)))))
 '(default ((t (:background "white" :foreground "black" :height 140 :family "Hack"))))
 '(org-quote ((t (:inherit variable-pitch :slant italic))))
 '(org-ellipsis ((t (:inherit shadow :background "white")))))

(provide-theme 'blendoit-light)
