(deftheme sd-compagnon
  "Created 2021-05-23.")

(custom-theme-set-faces
 'sd-compagnon
 '(cursor ((t (:background "red"))))
 '(fixed-pitch ((t (:family "Compagnon Medium"))))
 '(variable-pitch ((t (:family "Compagnon Roman"))))
 '(escape-glyph ((((background dark)) (:foreground "cyan")) (((type pc)) (:foreground "magenta")) (t (:foreground "brown"))))
 '(homoglyph ((((background dark)) (:foreground "cyan")) (((type pc)) (:foreground "magenta")) (t (:foreground "brown"))))
 '(minibuffer-prompt ((t (:inherit (org-meta-line)))))
 '(highlight ((t (:background "light goldenrod"))))
 '(region ((t (:extend t :background "light goldenrod"))))
 '(shadow ((t (:foreground "light slate gray"))))
 '(secondary-selection ((((class color) (min-colors 88) (background light)) (:extend t :background "yellow1")) (((class color) (min-colors 88) (background dark)) (:extend t :background "SkyBlue4")) (((class color) (min-colors 16) (background light)) (:extend t :background "yellow")) (((class color) (min-colors 16) (background dark)) (:extend t :background "SkyBlue4")) (((class color) (min-colors 8)) (:extend t :foreground "black" :background "cyan")) (t (:inverse-video t))))
 '(trailing-whitespace ((((class color) (background light)) (:background "red1")) (((class color) (background dark)) (:background "red1")) (t (:inverse-video t))))
 '(font-lock-builtin-face ((t (:foreground "light pink"))))
 '(font-lock-comment-delimiter-face ((t (:foreground "slate gray" :inherit (fixed-pitch)))))
 '(font-lock-comment-face ((t (:family "Compagnon Bold"))))
 '(font-lock-constant-face ((t (:foreground "saddle brown" :weight bold))))
 '(font-lock-doc-face ((t (:inherit variable-pitch))))
 '(font-lock-function-name-face ((t (:foreground "RosyBrown3" :weight bold))))
 '(font-lock-keyword-face ((t (:foreground "pink4"))))
 '(font-lock-negation-char-face ((t nil)))
 '(font-lock-preprocessor-face ((t (:inherit (font-lock-builtin-face)))))
 '(font-lock-regexp-grouping-backslash ((t (:foreground "orange"))))
 '(font-lock-regexp-grouping-construct ((t (:foreground "dark orange"))))
 '(font-lock-string-face ((t (:inherit variable-pitch))))
 '(font-lock-type-face ((t (:foreground "orchid2"))))
 '(font-lock-variable-name-face ((t (:weight bold))))
 '(font-lock-warning-face ((t (:inherit (error)))))
 '(button ((t (:inherit link))))
 '(link ((t (:family "Compagnon Light Italic"))))
 '(link-visited ((t (:inherit link))))
 '(fringe ((t (:background "gainsboro"))))
 '(header-line ((t (:height 1.8 :weight bold :inherit org-meta-line))))
 '(tooltip ((t (:background "old lace" :foreground "black" :family "Hermit"))))
 '(mode-line ((t (:inherit org-meta-line :box (:line-width -1 :style released-button)))))
 '(mode-line-buffer-id ((t (:weight bold))))
 '(mode-line-emphasis ((t (:weight bold))))
 '(mode-line-highlight ((((class color) (min-colors 88)) (:box (:line-width 2 :color "grey40" :style released-button))) (t (:inherit (highlight)))))
 '(mode-line-inactive ((t (:box (:line-width -1 :color "dark gray" :style nil) :background "gainsboro" :inherit (org-meta-line)))))
 '(isearch ((t (:foreground "white" :background "DodgerBlue1"))))
 '(isearch-fail ((((class color) (min-colors 88) (background light)) (:background "RosyBrown1")) (((class color) (min-colors 88) (background dark)) (:background "red4")) (((class color) (min-colors 16)) (:background "red")) (((class color) (min-colors 8)) (:background "red")) (((class color grayscale)) (:foreground "grey")) (t (:inverse-video t))))
 '(lazy-highlight ((t (:foreground "burlywood" :box 2))))
 '(match ((t (:background "yellow1"))))
 '(next-error ((t (:inherit (region)))))
 '(query-replace ((t (:inherit (isearch)))))
 '(org-meta-line ((t (:extend t :background "burlywood2" :family "Compagnon Light"))))
 '(org-table ((t (:inherit fixed-pitch :background "lemon chiffon"))))
 '(org-block ((t (:inherit fixed-pitch :extend t))))
 '(org-code ((t (:inherit fixed-pitch))))
 '(custom-variable-tag ((t (:weight bold))))
 '(org-block-begin-line ((t (:inherit org-meta-line :extend t :background "lemon chiffon"))))
 '(org-block-end-line ((t (:extend t :inherit org-block-begin-line))))
 '(outline-1 ((t (:family "Compagnon Medium"))))
 '(outline-2 ((t (:inherit outline-1))))
 '(outline-3 ((t (:inherit outline-1))))
 '(outline-4 ((t (:inherit outline-1))))
 '(outline-5 ((t (:inherit outline-1))))
 '(outline-6 ((t (:inherit outline-1))))
 '(outline-7 ((t (:inherit outline-1))))
 '(outline-8 ((t (:inherit outline-1))))
 '(org-special-keyword ((t (:inherit fixed-pitch :foreground "black" :background "cornsilk"))))
 '(line-number ((t (:inherit org-meta-line))))
 '(org-todo ((t (:inherit fixed-pitch :background "tomato" :foreground "white" :weight bold))))
 '(org-done ((t (:weight bold :foreground "white" :background "medium aquamarine" :inherit fixed-pitch))))
 '(org-date ((t (:inherit link))))
 '(bold ((t (:weight bold))))
 '(italic ((t (:slant italic))))
 '(bold-italic ((t (:slant italic :weight bold))))
 '(org-headline-done ((t (:foreground "aquamarine4" :inherit outline-1))))
 '(org-footnote ((t (:family "Compagnon Light"))))
 '(custom-link ((t (:inherit fixed-pitch :background "burlywood1"))))
 '(show-paren-match ((t (:background "aquamarine"))))
 '(show-paren-mismatch ((t (:background "orange red" :foreground "white"))))
 '(default ((t (:inherit nil :extend nil :stipple nil :background "cornsilk" :foreground "black" :inverse-video nil :box nil :strike-through nil :overline nil :underline nil :slant normal :weight semi-bold :height 142 :width normal :foundry "UKWN" :family "Compagnon Medium"))))
 '(org-drawer ((t (:inherit org-block-begin-line)))))

(provide-theme 'sd-compagnon)
