(deftheme sd-dark
  "Created 2021-05-09.")

(custom-theme-set-faces
 'sd-dark
 '(Info-quoted ((t (:inherit org-block))))
 '(cursor ((t (:background "red"))))
 '(erc-action-face ((t (:slant italic))))
 '(erc-button ((t (:inherit link))))
 '(erc-input-face ((t (:foreground "DarkOrchid4"))))
 '(erc-nick-default-face ((t (:inherit org-meta-line :weight bold))))
 '(erc-notice-face ((t (:inherit shadow))))
 '(erc-timestamp-face ((t (:inherit org-meta-line))))
 '(escape-glyph ((((background dark)) (:foreground "cyan")) (((type pc)) (:foreground "magenta")) (t (:foreground "brown"))))
 '(fixed-pitch ((t (:family "Hack"))))
 '(font-lock-builtin-face ((t (:foreground "medium purple"))))
 '(font-lock-comment-delimiter-face ((t (:inherit fixed-pitch :foreground "slate gray"))))
 '(font-lock-comment-face ((t (:inherit fixed-pitch :foreground "light slate gray" :slant italic))))
 '(font-lock-constant-face ((t (:foreground "MediumOrchid4"))))
 '(font-lock-doc-face ((t (:weight normal :inherit variable-pitch :foreground "white"))))
 '(font-lock-function-name-face ((t (:foreground "medium violet red" :weight bold))))
 '(font-lock-keyword-face ((t (:foreground "violet"))))
 '(font-lock-negation-char-face ((t nil)))
 '(font-lock-preprocessor-face ((t (:inherit font-lock-builtin-face))))
 '(font-lock-regexp-grouping-backslash ((t (:inherit bold :foreground "dark orange"))))
 '(font-lock-regexp-grouping-construct ((t (:inherit bold))))
 '(font-lock-string-face ((t (:foreground "MediumOrchid3"))))
 '(font-lock-type-face ((t (:foreground "orchid2"))))
 '(font-lock-variable-name-face ((t (:foreground "DarkOrchid3" :weight bold))))
 '(font-lock-warning-face ((t (:inherit error))))
 '(fringe ((t (:background "grey10"))))
 '(header-line ((t (:weight extra-bold :height 1.8 :family "Public Sans"))))
 '(highlight ((t (:background "LightSkyBlue1"))))
 '(homoglyph ((((background dark)) (:foreground "cyan")) (((type pc)) (:foreground "magenta")) (t (:foreground "brown"))))
 '(isearch ((t (:background "DodgerBlue1" :foreground "white"))))
 '(isearch-fail ((t (:background "RosyBrown1"))))
 '(ivy-minibuffer-match-face-1 ((t (:inherit swiper-match-face-1))))
 '(ivy-minibuffer-match-face-2 ((t (:inherit swiper-match-face-2))))
 '(ivy-minibuffer-match-face-3 ((t (:inherit swiper-match-face-3))))
 '(ivy-minibuffer-match-face-4 ((t (:inherit swiper-match-face-4))))
 '(ivy-minibuffer-match-highlight ((t (:inherit highlight))))
 '(lazy-highlight ((t (:foreground "DodgerBlue1" :box 2))))
 '(match ((t (:background "yellow1"))))
 '(minibuffer-prompt ((t (:inherit org-meta-line))))
 '(mode-line ((t (:height 1.2 :family "Hack" :background "steel blue" :foreground "white" :box (:line-width -1 :style released-button)))))
 '(mode-line-buffer-id ((t (:weight bold))))
 '(mode-line-emphasis ((t (:weight bold))))
 '(mode-line-highlight ((t (:box (:line-width 2 :color "grey40" :style released-button)))))
 '(mode-line-inactive ((t (:height 1.2 :family "Hack" :background "SteelBlue4" :foreground "gainsboro" :box (:line-width -1 :color "gainsboro")))))
 '(next-error ((t (:inherit region))))
 '(org-block ((t (:foreground "light slate blue" :background "smoke" :inherit fixed-pitch))))
 '(org-checkbox ((t (:weight bold :inherit org-meta-line))))
 '(org-code ((t (:background "gainsboro" :foreground "black" :family "Hack"))))
 '(org-date ((t (:inherit (link fixed-pitch)))))
 '(org-document-info ((t (:weight bold))))
 '(org-document-info-keyword ((t (:inherit org-meta-line))))
 '(org-document-title ((t (:weight bold :height 2.4))))
 '(org-done ((t (:background "forest green" :foreground "white" :weight bold :height 1.4 :family "hermit"))))
 '(org-drawer ((t (:inherit org-meta-line))))
 '(org-ellipsis ((t (:background "grey20" :inherit shadow))))
 '(org-footnote ((t (:inherit (link variable-font)))))
 '(org-formula ((t (:inherit org-table))))
 '(org-level-1 ((t (:height 1.8))))
 '(org-level-2 ((t (:height 1.6))))
 '(org-level-3 ((t (:height 1.4))))
 '(org-level-4 ((t (:height 1.0))))
 '(org-level-5 ((t (:inherit org-level-4))))
 '(org-level-6 ((t (:inherit org-level-4))))
 '(org-level-7 ((t (:inherit org-level-4))))
 '(org-level-8 ((t (:inherit org-level-4))))
 '(org-meta-line ((t (:foreground "SteelBlue" :family "Hermit"))))
 '(org-priority ((t (:background "grey20" :inherit org-meta-line))))
 '(org-quote ((t (:inherit variable-pitch :slant italic))))
 '(org-special-keyword ((t (:background "grey20" :weight bold :inherit org-meta-line))))
 '(org-table ((t (:family "Hack"))))
 '(org-tag ((t (:inherit (link fixed-pitch)))))
 '(org-todo ((t (:background "tomato" :foreground "white" :weight bold :height 1.4 :family "Hermit"))))
 '(org-verbatim ((t (:background "grey20" :foreground "DodgerBlue1" :foundry "Hack"))))
 '(query-replace ((t (:inherit (isearch)))))
 '(region ((t (:background "gainsboro"))))
 '(secondary-selection ((((class color) (min-colors 88) (background light)) (:background "yellow1")) (((class color) (min-colors 88) (background dark)) (:background "SkyBlue4")) (((class color) (min-colors 16) (background light)) (:background "yellow")) (((class color) (min-colors 16) (background dark)) (:background "SkyBlue4")) (((class color) (min-colors 8)) (:foreground "black" :background "cyan")) (t (:inverse-video t))))
 '(shadow ((t (:foreground "light slate gray"))))
 '(swiper-match-face-1 ((t (:inherit lazy-highlight))))
 '(swiper-match-face-2 ((t (:inherit isearch))))
 '(swiper-match-face-3 ((t (:foreground "chocolate" :inherit isearch))))
 '(swiper-match-face-4 ((t (:foreground "yellow" :inherit isearch))))
 '(tooltip ((t (:background "gainsboro" :foreground "black" :family "Hermit"))))
 '(trailing-whitespace ((((class color) (background light)) (:background "red1")) (((class color) (background dark)) (:background "red1")) (t (:inverse-video t))))
 '(variable-pitch ((t (:family "Public Sans"))))
 '(line-number ((t (:background "grey15" :foreground "LightSteelBlue3" :weight normal :height 0.8 :family "Hack"))))
 '(show-paren-match ((t (:inherit highlight))))
 '(show-paren-mismatch ((t (:background "red" :foreground "grey20"))))
 '(widget-field ((t (:extend t :background "LightSteelBlue2"))))
 '(default ((t (:background "grey20" :foreground "white" :height 142 :family "Hack")))))

(provide-theme 'sd-dark)
