(deftheme sd-light
  "Created 2021-05-15.")

(custom-theme-set-faces
 'sd-light
 '(Info-quoted ((t (:inherit org-block))))
 '(cursor ((t (:background "red"))))
 '(erc-action-face ((t (:slant italic))))
 '(erc-button ((t (:inherit link))))
 '(erc-input-face ((t (:foreground "DarkOrchid4"))))
 '(erc-nick-default-face ((t (:inherit org-meta-line :weight bold))))
 '(erc-notice-face ((t (:inherit shadow))))
 '(erc-timestamp-face ((t (:inherit org-meta-line))))
 '(escape-glyph ((((background dark)) (:foreground "cyan")) (((type pc)) (:foreground "magenta")) (t (:foreground "brown"))))
 '(fixed-pitch ((t (:family "Hack"))))
 '(font-lock-builtin-face ((t (:foreground "medium purple"))))
 '(font-lock-comment-delimiter-face ((t (:inherit fixed-pitch :foreground "slate gray"))))
 '(font-lock-comment-face ((t (:inherit org-meta-line :background "white" :slant italic))))
 '(font-lock-constant-face ((t (:foreground "MediumOrchid4"))))
 '(font-lock-doc-face ((t (:foreground "midnight blue" :slant italic))))
 '(font-lock-function-name-face ((t (:foreground "medium violet red" :weight bold))))
 '(font-lock-keyword-face ((t (:foreground "violet" :weight bold))))
 '(font-lock-negation-char-face ((t nil)))
 '(font-lock-preprocessor-face ((t (:inherit font-lock-builtin-face))))
 '(font-lock-regexp-grouping-backslash ((t (:foreground "dark orange" :weight bold))))
 '(font-lock-regexp-grouping-construct ((t (:weight bold))))
 '(font-lock-string-face ((t (:foreground "MediumOrchid3"))))
 '(font-lock-type-face ((t (:foreground "orchid2"))))
 '(font-lock-variable-name-face ((t (:foreground "DarkOrchid3" :weight bold))))
 '(font-lock-warning-face ((t (:inherit (error)))))
 '(fringe ((t (:background "gainsboro"))))
 '(header-line ((t (:inherit org-meta-line :weight extra-bold :height 1.8))))
 '(highlight ((t (:background "LightSkyBlue1"))))
 '(homoglyph ((((background dark)) (:foreground "cyan")) (((type pc)) (:foreground "magenta")) (t (:foreground "brown"))))
 '(isearch ((t (:background "DodgerBlue1" :foreground "white"))))
 '(isearch-fail ((t (:background "RosyBrown1"))))
 '(ivy-minibuffer-match-face-1 ((t (:inherit swiper-match-face-1))))
 '(ivy-minibuffer-match-face-2 ((t (:inherit swiper-match-face-2))))
 '(ivy-minibuffer-match-face-3 ((t (:inherit swiper-match-face-3))))
 '(ivy-minibuffer-match-face-4 ((t (:inherit swiper-match-face-4))))
 '(ivy-minibuffer-match-highlight ((t (:inherit highlight))))
 '(lazy-highlight ((t (:foreground "DodgerBlue1" :box 2))))
 '(match ((t (:background "yellow1"))))
 '(minibuffer-prompt ((t (:inherit org-meta-line))))
 '(mode-line ((t (:inherit org-meta-line :box (:line-width -1 :style released-button)))))
 '(mode-line-buffer-id ((t (:weight bold))))
 '(mode-line-emphasis ((t (:weight bold))))
 '(mode-line-highlight ((t (:box (:line-width 2 :color "grey40" :style released-button)))))
 '(mode-line-inactive ((t (:inherit org-meta-line :background "gainsboro" :box (:line-width -1 :color "dark gray")))))
 '(next-error ((t (:inherit region))))
 '(org-block ((t (:inherit fixed-pitch :background "snow" :foreground "plum"))))
 '(org-checkbox ((t (:inherit org-meta-line :weight bold))))
 '(org-code ((t (:background "gainsboro" :foreground "black" :family "Hack"))))
 '(org-date ((t (:inherit (link fixed-pitch)))))
 '(org-document-info ((t (:weight bold))))
 '(org-document-info-keyword ((t (:inherit org-meta-line))))
 '(org-document-title ((t (:weight bold :height 2.4))))
 '(org-done ((t (:background "forest green" :foreground "white" :weight bold :height 1.6 :family "hermit"))))
 '(org-drawer ((t (:inherit org-meta-line))))
 '(org-ellipsis ((t (:inherit shadow :background "white"))))
 '(org-footnote ((t (:inherit (link variable-font)))))
 '(org-formula ((t (:slant italic :inherit org-table))))
 '(org-level-1 ((t (:height 1.8))))
 '(org-level-2 ((t (:height 1.6))))
 '(org-level-3 ((t (:height 1.4))))
 '(org-level-4 ((t (:height 1.0))))
 '(org-level-5 ((t (:inherit org-level-4))))
 '(org-level-6 ((t (:inherit org-level-4))))
 '(org-level-7 ((t (:inherit org-level-4))))
 '(org-level-8 ((t (:inherit org-level-4))))
 '(org-meta-line ((t (:extend t :background "white smoke" :foreground "LightSteelBlue3" :family "Hermit"))))
 '(org-priority ((t (:inherit org-special-keyword :height 1.6))))
 '(org-quote ((t (:inherit variable-pitch :slant italic))))
 '(org-special-keyword ((t (:inherit org-meta-line :weight bold :background "white"))))
 '(org-table ((t (:height 0.8 :family "Hack"))))
 '(org-tag ((t (:inherit (link fixed-pitch)))))
 '(org-todo ((t (:background "tomato" :foreground "white" :weight bold :height 1.6 :family "Hermit"))))
 '(org-verbatim ((t (:foundry "Hack" :foreground "DodgerBlue1" :background "white" :inherit org-code))))
 '(query-replace ((t (:inherit (isearch)))))
 '(region ((t (:background "gainsboro"))))
 '(secondary-selection ((((class color) (min-colors 88) (background light)) (:background "yellow1")) (((class color) (min-colors 88) (background dark)) (:background "SkyBlue4")) (((class color) (min-colors 16) (background light)) (:background "yellow")) (((class color) (min-colors 16) (background dark)) (:background "SkyBlue4")) (((class color) (min-colors 8)) (:foreground "black" :background "cyan")) (t (:inverse-video t))))
 '(shadow ((t (:foreground "light slate gray"))))
 '(swiper-match-face-1 ((t (:foreground "red"))))
 '(swiper-match-face-2 ((t (:foreground "orange red"))))
 '(swiper-match-face-3 ((t (:foreground "chocolate"))))
 '(swiper-match-face-4 ((t (:foreground "yellow"))))
 '(tooltip ((t (:background "gainsboro" :foreground "black" :family "Hermit"))))
 '(trailing-whitespace ((((class color) (background light)) (:background "red1")) (((class color) (background dark)) (:background "red1")) (t (:inverse-video t))))
 '(variable-pitch ((t (:foreground "black" :height 1.2 :family "Public Sans"))))
 '(line-number ((t (:height 0.8 :inherit org-meta-line))))
 '(show-paren-match ((t (:inherit highlight))))
 '(show-paren-mismatch ((t (:background "red" :foreground "white"))))
 '(widget-field ((t (:extend t :background "LightSteelBlue2"))))
 '(swiper-line-face ((t (:inherit (highlight)))))
 '(swiper-background-match-face-1 ((t (:background "cyan"))))
 '(swiper-background-match-face-2 ((t (:background "chartreuse"))))
 '(swiper-background-match-face-3 ((t (:background "orange"))))
 '(swiper-background-match-face-4 ((t (:background "magenta"))))
 '(org-headline-done ((t (:foreground "PaleGreen3" :height 1.6))))
 '(default ((t (:background "white" :foreground "dark slate blue" :height 142 :family "Hack")))))

(provide-theme 'sd-light)
